# Generated by Django 4.2.7 on 2023-11-20 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('Name', models.CharField(max_length=100)),
                ('Email', models.EmailField(max_length=254, validators=[django.core.validators.EmailValidator(message='Invalid Email')])),
                ('Notes', models.CharField(max_length=500)),
            ],
        ),
    ]
