# Generated by Django 4.2.7 on 2023-12-03 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='record',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
