# Generated by Django 4.2.7 on 2023-12-03 09:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0002_record_update_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='record',
            name='update_date',
        ),
        migrations.AlterField(
            model_name='record',
            name='Email',
            field=models.EmailField(max_length=254, unique=True, validators=[django.core.validators.EmailValidator(message='Invalid Email')]),
        ),
        migrations.AlterField(
            model_name='record',
            name='Name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
